COMPILER=gcc
CFLAGS=-ggdb -pedantic -Wall


all: simple_list2 simple_list3 simple_list4 simple_list5

simple_list2:
	$(COMPILER) $(CFLAGS) simple_list2.c -o simple_list2
	
simple_list3:    
	$(COMPILER) $(CFLAGS) simple_list3.c -o simple_list3

simple_list4:
	$(COMPILER) $(CFLAGS) simple_list4.c -o simple_list4

simple_list5:
	$(COMPILER) $(CFLAGS) simple_list5.c -o simple_list5
