COMPILER=gcc
CFLAGS=-ggdb -pedantic -Wall


all: simple_bst2 simple_bst3 simple_bst4 simple_bst5

simple_bst2:
	$(COMPILER) $(CFLAGS) simple_bst2.c -o simple_bst2
	
simple_bst3:    
	$(COMPILER) $(CFLAGS) simple_bst3.c -o simple_bst3

simple_bst4:
	$(COMPILER) $(CFLAGS) simple_bst4.c -o simple_bst4

simple_bst5:
	$(COMPILER) $(CFLAGS) simple_bst5.c -o simple_bst5