COMPILER=gcc
CFLAGS=-ggdb -pedantic -Wall

all:	examB_1 examB_2 examB_3 examB_4 examB_5

examB_1: examB_1.c
	$(COMPILER) $(CFLAGS) -lm examB_1.c -o eB1

examB_2: examB_2.c
	$(COMPILER) $(CFLAGS) examB_2.c -o eB2

examB_3: examB_3.c
	$(COMPILER) $(CFLAGS) /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/words.c /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/list.c examB_3.c -o eB3

examB_4: examB_4.c
	$(COMPILER) $(CFLAGS) /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/words.c /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/bst.c examB_4.c -o eB4

examB_5: examB_5.c
	$(COMPILER) $(CFLAGS) -lm examB_5.c -o eB5
