COMPILER=gcc
CFLAGS=-ggdb -pedantic -Wall

all:	examA_1 examA_2 examA_3 examA_4 examA_5

examA_1: examA_1.c
	$(COMPILER) $(CFLAGS) -lm examA_1.c -o examA_1

examA_2: examA_2.c
	$(COMPILER) $(CFLAGS) examA_2.c -o examA_2

examA_3: examA_3.c
	$(COMPILER) $(CFLAGS) /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/words.c /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/list.c examA_3.c -o examA_3

examA_4: examA_4.c
	$(COMPILER) $(CFLAGS) /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/words.c /u1/h0/jkinne/public_html/cs202-f2017/CLASS/DS/bst.c examA_4.c -o examA_4

examA_5: examA_5.c
	$(COMPILER) $(CFLAGS) -lm examA_5.c -o examA_5
